import { loader } from "fumadocs-core/source";
import { toFumadocsSource } from "fumadocs-mdx/runtime/server";

// The generated content source lives at ./.source (regenerated by
// `fumadocs-mdx`). `@` maps to src/, so it's imported by relative path.
import { blog, docs } from "../../.source/server";
import { resolveDocsIcon } from "./docs-icons.jsx";

// Docs and blog share the same MDX pipeline but are two independent Fumadocs
// sources with their own baseUrl. `docs` is a docs collection (folder tree +
// meta.json ordering); `blog` is a flat doc collection turned into a source
// here.
//
// `icon: resolveDocsIcon` installs Fumadocs' icon plugin, which calls the
// resolver for every file/folder/separator node in the docs page tree (never
// for `blogSource`, which has no `icon` option — the blog sidebar is
// unaffected). See src/lib/docs-icons.jsx for the fail-closed contract.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
  icon: resolveDocsIcon,
});

export const blogSource = loader({
  baseUrl: "/blog",
  source: toFumadocsSource(blog, []),
});

// Clean, agent-readable markdown for one page: a title + URL header block
// followed by the page's processed markdown (enabled via
// `includeProcessedMarkdown` in source.config.ts — read through the async
// `getText('processed')` method). Backs the per-page `.md` URLs and the
// combined /llms-full.txt corpus.
export async function getLLMText(page) {
  const header = [`# ${page.data.title}`, `URL: ${page.url}`];
  if (page.data.description) {
    header.push("", page.data.description);
  }
  let body = "";
  try {
    body = await page.data.getText("processed");
  } catch {
    body = page.data.description ?? "";
  }
  return `${header.join("\n")}\n\n${body}`.trim();
}
