"""Offline checks for the generated customer API reference and its guide links."""

from __future__ import annotations

import importlib.util
import json
import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_PATH = ROOT / "scripts" / "generate_openapi_reference.py"


def load_generator():
    spec = importlib.util.spec_from_file_location("openphonex_api_reference", GENERATOR_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ApiReferenceTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.generator = load_generator()
        cls.schema = cls.generator.load_json(ROOT / "api" / "openapi.json")
        cls.coverage = cls.generator.load_json(ROOT / "api" / "customer-api-coverage.json")

    def test_generated_reference_is_current(self) -> None:
        expected = self.generator.render(self.schema, self.coverage)
        actual = (ROOT / "content" / "docs" / "api-reference.mdx").read_text(encoding="utf-8")
        self.assertEqual(actual, expected)
        self.assertIn("{/* Generated by", actual)
        self.assertNotIn("<!-- Generated by", actual)

    def test_released_customer_application_operations_are_covered(self) -> None:
        covered = set(self.coverage["covered_customer_operations"])
        self.assertTrue(self.generator.REQUIRED_OPERATIONS <= covered)
        rendered = (ROOT / "content" / "docs" / "api-reference.mdx").read_text(encoding="utf-8")
        for operation in self.generator.REQUIRED_OPERATIONS:
            _method, path = operation.split(" ", 1)
            self.assertIn(f"`{path}`", rendered)

    def test_bootstrap_configuration_and_workflow_reads_are_publicly_documented(self) -> None:
        covered = set(self.coverage["covered_customer_operations"])
        expected = {
            "GET /v1/workspace-context",
            "GET /v1/agents/{agent_id}/voice-stack",
            "PATCH /v1/agents/{agent_id}/voice-stack",
            "GET /v1/agents/{agent_id}/workflow",
        }
        self.assertTrue(expected <= covered)
        rendered = (ROOT / "content" / "docs" / "api-reference.mdx").read_text(encoding="utf-8")
        for operation in expected:
            _method, path = operation.split(" ", 1)
            self.assertIn(f"`{path}`", rendered)

        endpoints = (ROOT / "content" / "docs" / "rest-endpoints.mdx").read_text(encoding="utf-8")
        workflows = (ROOT / "content" / "docs" / "agent-workflows.mdx").read_text(encoding="utf-8")
        self.assertIn("component_credential_bindings", endpoints)
        self.assertIn("never return a secret", endpoints)
        self.assertIn("workflow_state: \"not_created\"", endpoints)
        self.assertIn("no AI or provider call", workflows)

    def test_call_evidence_guide_explains_safe_per_turn_audio(self) -> None:
        calls = self.schema["paths"]["/v1/dashboard/calls"]["get"]
        self.assertIn("has_audio", calls["description"])
        guide = (ROOT / "content" / "docs" / "read-call-evidence.mdx").read_text(
            encoding="utf-8"
        )
        self.assertIn("has_audio", guide)
        self.assertIn("retention", guide)
        self.assertRegex(guide, r"do not get a\s+broken player")
        self.assertIn("never receives a recording bucket URL", guide)

    def test_post_call_analysis_version_is_documented_as_an_immutable_snapshot(self) -> None:
        for schema_name in ("PostCallExtractionResult", "PostCallAnalysis"):
            with self.subTest(schema=schema_name):
                description = self.schema["components"]["schemas"][schema_name]["properties"][
                    "analysis_version"
                ]["description"]
                self.assertIn("snapshotted when this extraction is enqueued", description)
                self.assertIn("never relabeled", description)

    def test_navigation_and_cross_links_expose_the_customer_guides(self) -> None:
        pages = json.loads((ROOT / "content" / "docs" / "meta.json").read_text(encoding="utf-8"))["pages"]
        for slug in (
            "integrations",
            "customer-applications",
            "post-call-results",
            "audio-environments",
            "voice-library",
            "api-reference",
        ):
            self.assertIn(slug, pages)

        guide_text = {
            slug: (ROOT / "content" / "docs" / f"{slug}.mdx").read_text(encoding="utf-8")
            for slug in ("integrations", "customer-applications", "post-call-results", "voice-library")
        }
        self.assertIn("openphonex.integration_tool_call", guide_text["integrations"])
        self.assertIn("X-Agent-Telco-Signature", guide_text["integrations"])
        self.assertIn("POST /v1/calls", guide_text["customer-applications"])
        self.assertIn("Idempotency-Key", guide_text["customer-applications"])
        self.assertIn("call.extraction.ready", guide_text["post-call-results"])
        self.assertIn("later OpenPhonex analysis release never", guide_text["post-call-results"])
        self.assertIn("/docs/post-call-results", guide_text["integrations"])
        self.assertIn("/docs/integrations", guide_text["customer-applications"])
        self.assertIn("complete cached catalog", guide_text["voice-library"])
        self.assertIn("up to 100", guide_text["voice-library"])
        self.assertIn("accessible provider window", guide_text["voice-library"])

    def test_audio_environment_guide_matches_the_customer_contract(self) -> None:
        catalogue = self.schema["paths"]["/v1/audio-environments"]["get"]
        self.assertEqual(catalogue["x-required-scopes"], ["account:read"])
        self.assertIn("503", catalogue["responses"])

        guide = (ROOT / "content" / "docs" / "audio-environments.mdx").read_text(encoding="utf-8")
        for phrase in (
            "audio_environment",
            "caller_environment",
            "noise_level",
            "non-blank",
            "barge-in",
            "list_audio_environments",
        ):
            self.assertIn(phrase, guide)

    def test_integration_attachment_guide_matches_the_openapi_agent_update(self) -> None:
        patch = self.schema["paths"]["/v1/agents/{agent_id}"]["patch"]
        self.assertEqual(patch["x-required-scopes"], ["agents:write"])
        self.assertEqual(
            patch["requestBody"]["content"]["application/json"]["schema"]["$ref"],
            "#/components/schemas/AgentUpdate",
        )
        attachment = self.schema["components"]["schemas"]["IntegrationActionAttachment"]
        self.assertEqual(
            attachment["required"],
            ["type", "name", "connection_id", "tool_id"],
        )

        integrations = (ROOT / "content" / "docs" / "integrations.mdx").read_text(encoding="utf-8")
        attachment_section = integrations.split("## Attach an Action to a hosted agent", 1)[1].split(
            "## What your adapter receives during a call", 1
        )[0]
        self.assertIn("`PATCH /v1/agents/{agent_id}`", attachment_section)
        self.assertIn('"type": "connection"', attachment_section)
        self.assertIn('"connection_id": "conn_123"', attachment_section)
        self.assertIn('"tool_id": "itool_123"', attachment_section)
        self.assertNotIn('"organization_id": "org_123"', attachment_section)
        self.assertNotIn('"project_id": "proj_123"', attachment_section)

    def test_new_guide_links_resolve_to_docs_pages(self) -> None:
        docs_dir = ROOT / "content" / "docs"
        for slug in ("integrations", "customer-applications", "post-call-results", "api-reference"):
            content = (docs_dir / f"{slug}.mdx").read_text(encoding="utf-8")
            linked_slugs = re.findall(r"\]\(/docs/([a-z0-9-]+)(?:[?#][^)]*)?\)", content)
            for linked_slug in linked_slugs:
                with self.subTest(page=slug, target=linked_slug):
                    self.assertTrue((docs_dir / f"{linked_slug}.mdx").is_file())


if __name__ == "__main__":
    unittest.main()
