#!/usr/bin/env python3
"""Generate the customer REST-reference page from the checked-in OpenAPI snapshot.

This repository deliberately keeps the generated machine-reference snapshot
separate from handwritten product guides.  The command is deterministic and
never fetches a deployed API, so it is suitable for ordinary local and CI
checks.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_PATH = ROOT / "api" / "openapi.json"
COVERAGE_PATH = ROOT / "api" / "customer-api-coverage.json"
OUTPUT_PATH = ROOT / "content" / "docs" / "api-reference.mdx"
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
REQUIRED_OPERATIONS = frozenset(
    {
        "GET /v1/integrations",
        "POST /v1/integrations",
        "GET /v1/integrations/{integration_id}/actions",
        "POST /v1/integrations/{integration_id}/actions",
        "POST /v1/integrations/{integration_id}/disable",
        "POST /v1/calls",
        "POST /v1/calls/{call_id}/cancel",
        "GET /v1/call-results",
        "GET /v1/agents/{agent_id}/post-call-extraction",
        "PATCH /v1/agents/{agent_id}/post-call-extraction",
        "GET /v1/calls/{call_id}/post-call-extraction",
        "GET /v1/agent-endpoints",
        "POST /v1/agent-endpoints",
        "GET /v1/webhook-deliveries",
    }
)


class ReferenceError(ValueError):
    """Raised when the checked-in reference inputs cannot form a safe page."""


def operation_key(method: str, path: str) -> str:
    return f"{method.upper()} {path}"


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise ReferenceError(f"missing required file: {path.relative_to(ROOT)}") from error
    except json.JSONDecodeError as error:
        raise ReferenceError(f"invalid JSON in {path.relative_to(ROOT)}: {error}") from error
    if not isinstance(value, dict):
        raise ReferenceError(f"{path.relative_to(ROOT)} must contain a JSON object")
    return value


def customer_operations(schema: dict[str, Any], coverage: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    paths = schema.get("paths")
    if not isinstance(paths, dict):
        raise ReferenceError("OpenAPI snapshot must contain a paths object")
    raw_coverage = coverage.get("covered_customer_operations")
    if not isinstance(raw_coverage, list) or not all(isinstance(item, str) for item in raw_coverage):
        raise ReferenceError("customer API coverage must contain covered_customer_operations")
    if len(raw_coverage) != len(set(raw_coverage)):
        raise ReferenceError("customer API coverage repeats an operation")
    covered = set(raw_coverage)
    missing_required = sorted(REQUIRED_OPERATIONS - covered)
    if missing_required:
        raise ReferenceError("customer API coverage is missing required operations: " + ", ".join(missing_required))

    operations: dict[str, tuple[str, str, dict[str, Any]]] = {}
    for path, path_item in paths.items():
        if not isinstance(path, str) or not isinstance(path_item, dict):
            continue
        for method in HTTP_METHODS:
            operation = path_item.get(method)
            if isinstance(operation, dict):
                operations[operation_key(method, path)] = (method.upper(), path, operation)

    unknown = sorted(covered - operations.keys())
    if unknown:
        raise ReferenceError("customer API coverage names operations absent from the snapshot: " + ", ".join(unknown))
    missing = sorted(REQUIRED_OPERATIONS - operations.keys())
    if missing:
        raise ReferenceError("OpenAPI snapshot is missing required operations: " + ", ".join(missing))
    return [operations[key] for key in sorted(covered, key=lambda item: (item.split(" ", 1)[1], item))]


def _cell(value: object) -> str:
    return " ".join(str(value or "").split()).replace("|", "\\|")


def _scopes(operation: dict[str, Any]) -> str:
    scopes = operation.get("x-required-scopes")
    if not isinstance(scopes, list) or not scopes:
        return "See the live OpenAPI operation"
    return ", ".join(f"`{_cell(scope)}`" for scope in scopes)


def render(schema: dict[str, Any], coverage: dict[str, Any]) -> str:
    info = schema.get("info") if isinstance(schema.get("info"), dict) else {}
    title = _cell(info.get("title") or "OpenPhonex API")
    version = _cell(info.get("version") or "")
    operations = customer_operations(schema, coverage)
    lines = [
        "---",
        "title: Generated API reference",
        "description: Customer REST operations generated deterministically from the checked-in canonical OpenAPI snapshot.",
        "icon: Terminal",
        "---",
        "",
        "{/* Generated by scripts/generate_openapi_reference.py. Do not edit by hand. */}",
        "",
        "This page is the customer-facing operation index generated from the checked-in",
        "OpenAPI snapshot. The running API's [live OpenAPI document](/control-plane/openapi.json)",
        "is canonical for exact request and response schemas. Handwritten guides explain the",
        "product model: [Integrations](/docs/integrations),",
        "[customer applications](/docs/customer-applications), and",
        "[post-call results](/docs/post-call-results).",
        "",
        f"Snapshot: `{title}`{f' v{version}' if version else ''}. This generated index includes only customer SDK operations; dashboard, operator, provider, and worker transport hooks are intentionally excluded.",
        "",
        "## Customer REST operations",
        "",
        "| Method | Path | Summary | Required scope |",
        "| --- | --- | --- | --- |",
    ]
    for method, path, operation in operations:
        lines.append(
            f"| `{method}` | `{_cell(path)}` | {_cell(operation.get('summary') or '—')} | {_scopes(operation)} |"
        )
    lines.extend(
        [
            "",
            "## Regeneration contract",
            "",
            "The API repository generates `/openapi.json` from its canonical schema. This docs",
            "repository checks in a snapshot so builds and reviews do not depend on the network.",
            "Refresh that snapshot from the reviewed API source, then run:",
            "",
            "```bash",
            "python3 scripts/generate_openapi_reference.py --check",
            "python3 -m unittest discover -s tests",
            "```",
            "",
            "If the snapshot contains a new customer route, update the conceptual guide that",
            "explains its product model as well. Do not hand-copy request schemas into prose.",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated page has drifted")
    args = parser.parse_args(argv)
    expected = render(load_json(SNAPSHOT_PATH), load_json(COVERAGE_PATH))
    actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if args.check:
        if actual != expected:
            print(
                "generated API reference is stale; run python3 scripts/generate_openapi_reference.py",
                file=sys.stderr,
            )
            return 1
        print("Generated API reference is current.")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ReferenceError as error:
        print(f"OPENAPI REFERENCE FAILED: {error}", file=sys.stderr)
        raise SystemExit(1) from error
